AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend com HTTP API, Lambda e Cognito Auth

Parameters:
  Env:
    Type: String
    Description: O ambiente de deploy (devel, prod, staging)
    Default: devel
    AllowedValues:
      - devel
      - prod

  MyUserPoolId:
    Type: String
    Description: ID do user pool do Cognito
  
  MyAppClientId:
    Type: String
    Description: ID do client app do Cognito
  
  SupabaseUrl:
    Type: String
    Description: URL do projeto Supabase
    NoEcho: true
  
  SupabaseKey:
    Type: String
    Description: Chave de API do Supabase (Anon ou Service)
    NoEcho: true
    
  MALClientId:
    Type: String
    Description: ClientID do MyAnimeList
    NoEcho: true
  
  MALClientSecret:
    Type: String
    Description: Client Secret do MyAnimeList
    NoEcho: true

Globals:
  Function:
    Timeout: 180
    MemorySize: 1024
    Runtime: python3.13
    Architectures:
      - arm64
    Environment:
      Variables:
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_KEY: !Ref SupabaseKey
        TABLE_NAME: !Ref TabelaDados
        MAL_CLIENT_ID: !Ref MALClientId
        MAL_CLIENT_SECRET: !Ref MALClientSecret

Resources:
  TabelaDados:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  TabelaDadosParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/mylib/${Env}/tabela_dados"
      Type: String
      Value: !Ref TabelaDados
      Description: "Nome dinâmico da tabela gerado pelo CloudFormation"

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Sub "${Env}"
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
      
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${MyUserPoolId}"
              audience:
                - !Ref MyAppClientId
        DefaultAuthorizer: CognitoAuthorizer
  
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mylib-common-layer
      Description: Utilitarios (Wrappers, Erros, Validadores)
      ContentUri: src/layers/common_layer/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
  
  RecommendationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mylib-recommendation-layer
      Description: Utilitarios (Wrappers, Erros, Validadores)
      ContentUri: src/layers/recommendation_layer/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-search"
      CodeUri: src/functions/system/search
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /search
            Method: GET

  CatalogAddItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-add-item-catalog"
      CodeUri: src/functions/catalog/add_item/
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /catalog
            Method: POST
    
  CatalogListItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-list-catalog-items"
      CodeUri: src/functions/catalog/list_items
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /catalog
            Method: GET

  CatalogDeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-delete-catalog-item"
      CodeUri: src/functions/catalog/delete_item/
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /catalog
            Method: DELETE
    
  CatalogUpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-update-catalog-item"
      CodeUri: src/functions/catalog/update_item/
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /catalog
            Method: PATCH
  
  CatalogSyncMALFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-sync-mal"  
      CodeUri: src/functions/catalog/sync_mal/
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /catalog/sync-mal
            Method: POST

  RecommendationsGetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-get-item-recommendations"
      CodeUri: src/functions/recommendations/by_item/
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
        - !Ref RecommendationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /recommendations/item
            Method: GET
  
  RecommendationsGetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mylib-${Env}-get-user-recommendations"
      CodeUri: src/functions/recommendations/by_user/
      Handler: handler.lambda_handler
      Layers:
        - !Ref CommonLayer
        - !Ref RecommendationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TabelaDados
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /recommendations/user
            Method: GET

Outputs:
  ApiEndpoint:
    Description: "URL da API HTTP"
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}"