AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend com HTTP API, Lambda e Cognito Auth

Parameters:
  MyUserPoolId:
    Type: String
    Description: ID do user pool do Cognito
  
  MyAppClientId:
    Type: String
    Description: ID do client app do Cognito
  
  SupabaseUrl:
    Type: String
    Description: URL do projeto Supabase
    NoEcho: true
  
  SupabaseKey:
    Type: String
    Description: Chave de API do Supabase (Anon ou Service)
    NoEcho: true

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.13
    Architectures:
      - x86_64
    Environment:
      Variables:
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_KEY: !Ref SupabaseKey
        TABLE_NAME: !Ref TabelaDados

Resources:
  TabelaDados:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
      
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${MyUserPoolId}"
              audience:
                - !Ref MyAppClientId
        DefaultAuthorizer: CognitoAuthorizer

  HeartbeatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/system
      Handler: heartbeat.lambda_handler
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /
            Method: GET
            Auth:
              Authorizer: NONE
  
  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/system
      Handler: search.lambda_handler
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /search
            Method: GET
            Auth:
              Authorizer: NONE


Outputs:
  ApiEndpoint:
    Description: "URL da API HTTP"
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"