create table public.midia (
  id bigint generated by default as identity not null,
  categoria text not null,
  titulo text not null,
  descricao text null,
  ano_lancamento integer null,
  imagem text null,
  metadata jsonb not null,
  generos text[] null,
  generos_unificados text[] null,
  rating numeric(3, 2) null,
  updated_at timestamp with time zone null default now(),
  classificacao integer null default 14,
  titulos_alternativos text[] null default '{}'::text[],
  constraint midia_pkey primary key (id),
  constraint unq_conteudo unique (categoria, titulo, ano_lancamento),
  constraint midia_rating_check check (
    (
      (rating >= (0)::numeric)
      and (rating <= (5)::numeric)
    )
  )
) TABLESPACE pg_default;


//-- Indexes and Functions for Text Search Optimization
CREATE OR REPLACE FUNCTION public.f_unaccent(text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
SET search_path = extensions, public, pg_catalog
AS $$
BEGIN
  RETURN extensions.unaccent($1);
end;
$$;

create index idx_midias_titulo_search 
on midia
using gin (f_unaccent(titulo) gin_trgm_ops);

CREATE OR REPLACE FUNCTION public.f_processar_alternativos(arr text[])
RETURNS text

LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE STRICT
AS $$
BEGIN
    IF arr IS NULL THEN
        RETURN '';
    END IF;
    RETURN extensions.unaccent(array_to_string(arr, ' '));
END;

create index IF not exists idx_midia_alternativos_trgm on public.midia using gin (
  f_processar_alternativos (titulos_alternativos) extensions.gin_trgm_ops
) TABLESPACE pg_default;

create index IF not exists idx_midia_titulo_trgm on public.midia using gin (f_unaccent (titulo) extensions.gin_trgm_ops) TABLESPACE pg_default;

create index IF not exists idx_midias_rating on public.midia using btree (rating) TABLESPACE pg_default;

create index IF not exists idx_midia_rating on public.midia using btree (rating desc nulls last) TABLESPACE pg_default;

create index IF not exists idx_midia_generos_gin on public.midia using gin (generos) TABLESPACE pg_default;

create index IF not exists idx_midia_categoria on public.midia using btree (categoria) TABLESPACE pg_default;

create index IF not exists idx_midia_cat_rating on public.midia using btree (categoria, rating desc) TABLESPACE pg_default;