GENRE_MAP = {
    "fps": ["Ação & Aventura"],
    "shooter": ["Ação & Aventura"],
    "plataforma": ["Ação & Aventura"],
    "rpg": ["Sci-Fi & Fantasia", "Estratégia & Puzzle"],
    "jrpg": ["Sci-Fi & Fantasia"],
    "action rpg": ["Ação & Aventura", "Sci-Fi & Fantasia"],
    "roguelike": ["Ação & Aventura", "Estratégia & Puzzle"],
    "metroidvania": ["Ação & Aventura"],
    "survival horror": ["Terror & Suspense", "Ação & Aventura"],
    "visual novel": ["Drama & Narrativo"],
    "puzzle": ["Estratégia & Puzzle"],
    "rts": ["Estratégia & Puzzle"],
    "moba": ["Estratégia & Puzzle", "Esportes & Competitivo"],
    "esporte": ["Esportes & Competitivo"],
    "corrida": ["Esportes & Competitivo", "Ação & Aventura"],
    "ação": ["Ação & Aventura"],
    "aventura": ["Ação & Aventura"],
    "ficção científica": ["Sci-Fi & Fantasia"],
    "fantasia": ["Sci-Fi & Fantasia"],
    "terror": ["Terror & Suspense"],
    "horror": ["Terror & Suspense"],
    "thriller": ["Terror & Suspense"],
    "policial": ["Terror & Suspense", "Drama & Narrativo"],
    "drama": ["Drama & Narrativo"],
    "comédia": ["Comédia & Slice of Life"],
    "romance": ["Romance", "Drama & Narrativo"],
    "documentário": ["Documentário & Educacional"],
    "animação": [],
    "slice of life": ["Comédia & Slice of Life"],
    "comédia romântica": ["Romance", "Comédia & Slice of Life"],
    "biografia": ["Documentário & Educacional", "Drama & Narrativo"],
    "técnico": ["Documentário & Educacional"],
    "autoajuda": ["Documentário & Educacional"],
    "distopia": ["Sci-Fi & Fantasia", "Drama & Narrativo"],
    "mistério": ["Terror & Suspense"],
    "young adult": ["Drama & Narrativo"],
    "poesia": ["Drama & Narrativo"],
    "contos": ["Drama & Narrativo"],
    "crônica": ["Drama & Narrativo", "Comédia & Slice of Life"],
    "ensaios": ["Documentário & Educacional", "Drama & Narrativo"],
    "clássicos": ["Drama & Narrativo"],
    "literatura brasileira": ["Drama & Narrativo"],
    "teatro": ["Drama & Narrativo"],
    "história": ["Documentário & Educacional"],
    "filosofia": ["Documentário & Educacional"],
    "sociologia": ["Documentário & Educacional"],
    "psicologia": ["Documentário & Educacional"],
    "política": ["Documentário & Educacional"],
    "negócios": ["Documentário & Educacional"],
    "economia": ["Documentário & Educacional"],
    "finanças": ["Documentário & Educacional"],
    "marketing": ["Documentário & Educacional"],
    "ciências": ["Documentário & Educacional"],
    "tecnologia": ["Documentário & Educacional"],
    "biologia": ["Documentário & Educacional"],
    "física": ["Documentário & Educacional"],
    "matemática": ["Documentário & Educacional"],
    "medicina": ["Documentário & Educacional", "Documentário & Educacional"],
    "saúde": ["Documentário & Educacional"],
    "bem-estar": ["Documentário & Educacional"],
    "esoterismo": ["Documentário & Educacional"],
    "religião": ["Documentário & Educacional"],
    "espiritualidade": ["Documentário & Educacional"],
    "viagem": ["Documentário & Educacional", "Ação & Aventura"],
    "culinária": ["Documentário & Educacional"],
    "gastronomia": ["Documentário & Educacional"],
    "arquitetura": ["Documentário & Educacional"],
    "arte": ["Documentário & Educacional", "Drama & Narrativo"],
    "design": ["Documentário & Educacional"],
    "fotografia": ["Documentário & Educacional"],
    "moda": ["Documentário & Educacional"],
    "jornalismo": ["Documentário & Educacional"],
    "true crime": ["Terror & Suspense", "Documentário & Educacional"],
    "romance de época": ["Romance", "Drama & Narrativo"],
    "romance histórico": ["Drama & Narrativo", "Ação & Aventura"],
    "chick-lit": ["Romance", "Comédia & Slice of Life"],
    "lad-lit": ["Romance", "Comédia & Slice of Life"],
    "erótico": ["Romance"],
    "new adult": ["Romance", "Drama & Narrativo"],
    "realismo mágico": ["Sci-Fi & Fantasia", "Drama & Narrativo"],
    "fantasia urbana": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "alta fantasia": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "dark fantasy": ["Sci-Fi & Fantasia", "Terror & Suspense"],
    "cyberpunk": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "steampunk": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "space opera": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "gótico": ["Terror & Suspense", "Drama & Narrativo"],
    "faroeste": ["Ação & Aventura"],
    "western": ["Ação & Aventura"],
    "guerra": ["Ação & Aventura", "Drama & Narrativo"],
    "hq": ["Ação & Aventura", "Sci-Fi & Fantasia"],
    "comics": ["Ação & Aventura", "Sci-Fi & Fantasia"],
    "mangá": ["Ação & Aventura", "Sci-Fi & Fantasia"],
    "graphic novel": ["Drama & Narrativo"],
    "webtoon": ["Romance", "Comédia & Slice of Life"],
}

ENGLISH_MOVIE_GENRE_ADDITIONS = {
    # --- Action & Adventure ---
    "action": ["Ação & Aventura"],
    "adventure": ["Ação & Aventura"],
    "superhero": ["Ação & Aventura", "Sci-Fi & Fantasia"],
    "martial arts": ["Ação & Aventura", "Esportes & Competitivo"],
    "spy": ["Ação & Aventura", "Terror & Suspense"],
    "espionage": ["Ação & Aventura", "Terror & Suspense"],
    "disaster": ["Ação & Aventura", "Drama & Narrativo"],
    "swashbuckler": ["Ação & Aventura"],  # Filmes de "capa e espada"
    "western": ["Ação & Aventura"],
    "war": ["Ação & Aventura", "Drama & Narrativo"],
    "survival": ["Ação & Aventura", "Terror & Suspense"],
    # --- Drama & Narrative ---
    "drama": ["Drama & Narrativo"],
    "epic": ["Drama & Narrativo", "Ação & Aventura"],
    "biography": ["Drama & Narrativo", "Documentário & Educacional"],
    "biopic": ["Drama & Narrativo", "Documentário & Educacional"],
    "history": ["Drama & Narrativo", "Documentário & Educacional"],
    "historical": ["Drama & Narrativo", "Ação & Aventura"],
    "period piece": ["Drama & Narrativo"],  # Filme de época
    "musical": ["Drama & Narrativo", "Romance"],
    "music": ["Drama & Narrativo"],
    "dance": ["Drama & Narrativo", "Esportes & Competitivo"],
    "legal": ["Drama & Narrativo", "Terror & Suspense"],  # Filmes de tribunal
    "courtroom": ["Drama & Narrativo", "Terror & Suspense"],
    "coming of age": ["Drama & Narrativo", "Comédia & Slice of Life"],
    "road movie": ["Drama & Narrativo", "Ação & Aventura"],
    "indie": ["Drama & Narrativo"],
    "art house": ["Drama & Narrativo"],
    # --- Comedy ---
    "comedy": ["Comédia & Slice of Life"],
    "parody": ["Comédia & Slice of Life"],
    "satire": ["Comédia & Slice of Life"],
    "slapstick": ["Comédia & Slice of Life"],  # "Besteirol"/Comédia física
    "dark comedy": ["Comédia & Slice of Life", "Terror & Suspense"],
    "black comedy": ["Comédia & Slice of Life", "Terror & Suspense"],
    "stand-up": ["Comédia & Slice of Life"],
    "family": ["Comédia & Slice of Life", "Ação & Aventura"],
    "rom-com": ["Romance", "Comédia & Slice of Life"],
    # --- Horror, Thriller & Crime ---
    "horror": ["Terror & Suspense"],
    "thriller": ["Terror & Suspense"],
    "slasher": ["Terror & Suspense"],
    "gore": ["Terror & Suspense"],
    "splatter": ["Terror & Suspense"],
    "found footage": ["Terror & Suspense"],
    "supernatural": ["Terror & Suspense", "Sci-Fi & Fantasia"],
    "zombie": ["Terror & Suspense", "Ação & Aventura"],
    "monster": ["Terror & Suspense", "Sci-Fi & Fantasia"],
    "psychological": ["Terror & Suspense", "Drama & Narrativo"],
    "mystery": ["Terror & Suspense", "Estratégia & Puzzle"],
    "detective": ["Terror & Suspense", "Estratégia & Puzzle"],
    "crime": ["Terror & Suspense", "Ação & Aventura"],
    "gangster": ["Ação & Aventura", "Terror & Suspense"],
    "noir": ["Terror & Suspense", "Drama & Narrativo"],
    "neo-noir": ["Terror & Suspense", "Drama & Narrativo"],
    # --- Sci-Fi & Fantasy ---
    "sci-fi": ["Sci-Fi & Fantasia"],
    "science fiction": ["Sci-Fi & Fantasia"],
    "fantasy": ["Sci-Fi & Fantasia"],
    "cyberpunk": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "post-apocalyptic": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "time travel": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "space opera": ["Sci-Fi & Fantasia", "Ação & Aventura"],
    "dystopian": ["Sci-Fi & Fantasia", "Drama & Narrativo"],
    # --- Documentary & Formats ---
    "documentary": ["Documentário & Educacional"],
    "mockumentary": ["Comédia & Slice of Life"],
    "nature": ["Documentário & Educacional"],
    "wildlife": ["Documentário & Educacional"],
    "short": ["Drama & Narrativo"],  # Curta-metragem
    "animation": [
        "Comédia & Slice of Life",
        "Ação & Aventura",
    ],  # Genérico, pois depende do filme
}

# Atualizando o mapa principal
GENRE_MAP |= ENGLISH_MOVIE_GENRE_ADDITIONS
