GENRE_MAP = {
    "fps": ["Ação & Aventura"],
    "shooter": ["Ação & Aventura"],
    "plataforma": ["Ação & Aventura"],
    "rpg": ["Sci-Fi & Fantasia", "Estratégia & Puzzle"],
    "jrpg": ["Sci-Fi & Fantasia"],
    "action rpg": ["Ação & Aventura", "Sci-Fi & Fantasia"],
    "roguelike": ["Ação & Aventura", "Estratégia & Puzzle"],
    "metroidvania": ["Ação & Aventura"],
    "survival horror": ["Terror & Suspense", "Ação & Aventura"],
    "visual novel": ["Drama & Narrativo"],
    "puzzle": ["Estratégia & Puzzle"],
    "rts": ["Estratégia & Puzzle"],
    "moba": ["Estratégia & Puzzle", "Esportes & Competitivo"],
    "esporte": ["Esportes & Competitivo"],
    "corrida": ["Esportes & Competitivo", "Ação & Aventura"],
    "ação": ["Ação & Aventura"],
    "aventura": ["Ação & Aventura"],
    "ficção científica": ["Sci-Fi & Fantasia"],
    "fantasia": ["Sci-Fi & Fantasia"],
    "terror": ["Terror & Suspense"],
    "horror": ["Terror & Suspense"],
    "thriller": ["Terror & Suspense"],
    "policial": ["Terror & Suspense", "Drama & Narrativo"],
    "drama": ["Drama & Narrativo"],
    "comédia": ["Comédia & Slice of Life"],
    "romance": ["Romance", "Drama & Narrativo"],
    "documentário": ["Documentário & Educacional"],
    "animação": [],
    "slice of life": ["Comédia & Slice of Life"],
    "comédia romântica": ["Romance", "Comédia & Slice of Life"],
    "guerra": ["Ação & Aventura", "Drama & Narrativo"],
    "biografia": ["Documentário & Educacional", "Drama & Narrativo"],
    "técnico": ["Documentário & Educacional"],
    "autoajuda": ["Documentário & Educacional"],
    "distopia": ["Sci-Fi & Fantasia", "Drama & Narrativo"],
    "mistério": ["Terror & Suspense"],
    "young adult": ["Drama & Narrativo"],
}
